import { ProfileData, Project } from "@/types";

export const initialProfile: ProfileData = {
  name: "Suriyakumar E",
  title: "Data Analytics | AI & ML Engineering Student",
  subtitle: "Transforming raw data into predictive intelligence and architecting forward-thinking AI & ML solutions.",
  status: "Open for AI & Data Analytics Internships & Research Collaborations",
  location: "Coimbatore, Tamil Nadu, India",
  email: "suryaaswin000@gmail.com",
  phone: "+91-9445648373",
  photo_url: "/images/suriyakumar-portrait.jpg",
  bio_paragraphs: [
    "Computer Science student specializing in Artificial Intelligence and Machine Learning, with foundational knowledge in data analytics. Experienced in Python, Pandas, NumPy, SQL, and Power BI through academic and real-world projects.",
    "Skilled in data analysis, visualization, and building high-impact interactive dashboards. Driven by an intense curiosity for mathematical modeling, vector retrieval, and generative AI systems.",
    "Passionate about leveraging cutting-edge AI technologies and data-driven solutions to solve complex hardware, web, and enterprise challenges."
  ],
  socials: {
    github: "https://github.com/SURIYAKUMARE",
    linkedin: "https://www.linkedin.com/in/suriyakumar-e-a1a236386",
    twitter: "https://twitter.com",
  },
  stats: [
    { number: "05", label: "Core Projects", sublabel: "Hardware, Web & AI" },
    { number: "08+", label: "Certifications", sublabel: "Google, Microsoft & RAG" },
    { number: "95%+", label: "Model Precision", sublabel: "In academic benchmarks" },
    { number: "2026", label: "YUDHISTRA Award", sublabel: "Distinguished Honor" },
  ],
  skills: [
    {
      category: "Data Analytics & BI",
      items: [
        { name: "SQL (Postgres / MySQL)", level: 92 },
        { name: "Pandas & NumPy", level: 95 },
        { name: "Power BI Dashboards", level: 90 },
        { name: "Microsoft Excel (Advanced)", level: 94 },
        { name: "Data Visualization", level: 90 },
      ],
    },
    {
      category: "AI & Machine Learning",
      items: [
        { name: "Python (AI / ML Core)", level: 96 },
        { name: "OpenCV & Face Recognition", level: 92 },
        { name: "Predictive Analytics", level: 88 },
        { name: "Vector Databases & RAG", level: 85 },
        { name: "C++ / Java", level: 84 },
      ],
    },
    {
      category: "Database & Developer Tools",
      items: [
        { name: "Git & GitHub", level: 90 },
        { name: "MongoDB", level: 85 },
        { name: "Jupyter Notebooks", level: 95 },
        { name: "VS Code & CLI", level: 92 },
        { name: "Design Thinking", level: 88 },
      ],
    },
  ],
  education: [
    {
      id: "edu-1",
      degree: "B.E. Computer Science & Engineering (AI & ML)",
      institution: "Rathinam Technical Campus",
      location: "Coimbatore, Tamil Nadu",
      period: "2025 — 2029",
      description:
        "Specializing in Artificial Intelligence, Machine Learning algorithms, Big Data engineering, Neural Networks, and mathematical statistics.",
      highlights: [
        "Specialization in Artificial Intelligence & Machine Learning",
        "Data structures, algorithms, and predictive systems",
        "Active contributor in technical symposiums and innovation labs",
      ],
    },
    {
      id: "edu-2",
      degree: "Higher Secondary Certificate (HSC)",
      institution: "Harvard Hi-Tech Matric Higher Secondary School",
      location: "Tamil Nadu, India",
      period: "Completed 2024",
      description:
        "Rigorous foundation in Higher Mathematics, Physics, Chemistry, and Computer Science fundamentals.",
      highlights: [
        "Strong academic track record in Mathematics and Science",
        "Early foundation in algorithmic logic and computational problem solving",
      ],
    },
  ],
  certifications: [
    {
      id: "cert-1",
      title: "Google Data Analytics Professional Certificate",
      issuer: "Google",
      year: "2025",
      category: "Data Analytics",
    },
    {
      id: "cert-2",
      title: "Microsoft AI Learning Activities",
      issuer: "Microsoft",
      year: "2025",
      category: "AI & ML",
    },
    {
      id: "cert-3",
      title: "Advanced RAG Applications with Vector Databases",
      issuer: "Leading AI Institute",
      year: "2026",
      category: "AI & ML",
    },
    {
      id: "cert-4",
      title: "Process Data from Dirty to Clean",
      issuer: "Google Career Certificates",
      year: "2025",
      category: "Data Analytics",
    },
    {
      id: "cert-5",
      title: "Advanced Diploma in Data Analytics",
      issuer: "Professional Analytics Board",
      year: "2025",
      category: "Data Analytics",
    },
    {
      id: "cert-6",
      title: "Introduction to Artificial Intelligence",
      issuer: "AI Research Academy",
      year: "2024",
      category: "AI & ML",
    },
    {
      id: "cert-7",
      title: "Design Thinking and Innovation",
      issuer: "Innovation Cell",
      year: "2025",
      category: "Innovation & Honours",
    },
    {
      id: "cert-8",
      title: "YUDHISTRA 2K26 AWARD",
      issuer: "Technical Symposium & Innovation Conclave",
      year: "2026",
      featuredAward: true,
      category: "Innovation & Honours",
    },
  ],
};

export const initialProjects: Project[] = [
  {
    id: "proj-1",
    eyebrow: "PROJECT 01",
    title: "NSG Live Location Tracking",
    shortDescription: "Hardware-based GPS asset telemetry and ultra-low latency coordinate streaming.",
    description: "A physical hardware tracking apparatus combining high-precision GPS modules, SIM/Cellular transceivers, and microcontrollers. Streams real-time geospatial telemetry directly to an interactive telemetry command dashboard with geofencing and motion detection.",
    technicalCallout: "Hardware GPS Telemetry Engine",
    calloutDetail: "Custom firmware written in C++ and Python streaming continuous NMEA coordinates with sub-2s latency and 2.5m precision.",
    category: "Web & IoT",
    image: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?q=80&w=1600&auto=format&fit=crop",
    zoomImage: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1600&auto=format&fit=crop",
    githubUrl: "https://github.com/SURIYAKUMARE",
    liveUrl: "https://github.com/SURIYAKUMARE",
    featured: true,
    order_index: 1,
    year: "2026",
    client: "Hardware & IoT Innovation",
    role: "Lead Hardware & Telemetry Architect",
    technologies: ["IoT / Microcontrollers", "GPS Telemetry", "Python", "WebSockets", "C++"],
    metrics: [
      { label: "Update Rate", value: "< 2s Interval" },
      { label: "Precision", value: "~ 2.5m GPS" },
    ],
    awards: ["Hardware Innovation Showcase"],
  },
  {
    id: "proj-2",
    eyebrow: "PROJECT 02",
    title: "Cotsify.shop",
    shortDescription: "Modern high-throughput e-commerce web application with reactive storefront architecture.",
    description: "A full-stack digital boutique built with dynamic product catalogs, persistent cart state synchronization, secure checkout pipelines, and mobile-first responsive interfaces.",
    technicalCallout: "Reactive Cart & Storefront Architecture",
    calloutDetail: "Engineered on React and Node.js with MongoDB indexing, achieving 98/100 Lighthouse performance and sub-150ms client render latency.",
    category: "Web & IoT",
    image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=1600&auto=format&fit=crop",
    zoomImage: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1600&auto=format&fit=crop",
    githubUrl: "https://github.com/SURIYAKUMARE",
    liveUrl: "https://cotsify.shop",
    featured: true,
    order_index: 2,
    year: "2025",
    client: "Cotsify Digital",
    role: "Full-Stack Web Developer",
    technologies: ["React", "JavaScript", "Node.js", "MongoDB", "Tailwind CSS"],
    metrics: [
      { label: "Mobile Score", value: "98/100" },
      { label: "Availability", value: "99.9%" },
    ],
  },
  {
    id: "proj-3",
    eyebrow: "PROJECT 03",
    title: "Student Performance Analysis",
    shortDescription: "Exploratory statistical modeling and interactive Power BI diagnostic dashboards.",
    description: "End-to-end data analytics workflow ingesting institutional academic records. Cleanses dirty inputs, correlates attendance, study frequency, and socioeconomic indicators with semester outcomes, and delivers visual Power BI reporting.",
    technicalCallout: "Multivariate Regression & BI Intelligence",
    calloutDetail: "Processed 10,000+ student observations using Pandas and NumPy with an R² correlation of 0.89 and automated data cleansing routines.",
    category: "Data Analytics",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=1600&auto=format&fit=crop",
    zoomImage: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?q=80&w=1600&auto=format&fit=crop",
    githubUrl: "https://github.com/SURIYAKUMARE",
    liveUrl: "https://github.com/SURIYAKUMARE",
    featured: true,
    order_index: 3,
    year: "2025",
    client: "Academic Research",
    role: "Data Analyst & Model Architect",
    technologies: ["Python", "Pandas", "NumPy", "Power BI", "SQL", "Matplotlib"],
    metrics: [
      { label: "Records Ingested", value: "10k+ Rows" },
      { label: "Correlation R²", value: "0.89" },
    ],
    awards: ["Academic Analytics Distinction"],
  },
  {
    id: "proj-4",
    eyebrow: "PROJECT 04",
    title: "Hostel Complaint Management System",
    shortDescription: "Automated campus issue triage, ticket lifecycle tracking, and administrative escalation.",
    description: "A centralized platform enabling university students to log infrastructure, maintenance, and facility complaints with real-time status updates, SLA notifications, and administrative analytics.",
    technicalCallout: "Role-Based Escalation System",
    calloutDetail: "Built with relational SQL integrity and automated priority dispatching, reducing complaint resolution turnaround time by 65%.",
    category: "Full-Stack",
    image: "https://images.unsplash.com/photo-1522071820081-009f0129c71c?q=80&w=1600&auto=format&fit=crop",
    zoomImage: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=1600&auto=format&fit=crop",
    githubUrl: "https://github.com/SURIYAKUMARE",
    liveUrl: "https://github.com/SURIYAKUMARE",
    featured: true,
    order_index: 4,
    year: "2025",
    client: "University Campus Operations",
    role: "Full-Stack Software Engineer",
    technologies: ["Python", "SQL", "Flask / Node.js", "Tailwind CSS", "Role-Based Auth"],
    metrics: [
      { label: "Resolution Lift", value: "+65% Faster" },
      { label: "Active Students", value: "1,200+ Users" },
    ],
  },
  {
    id: "proj-5",
    eyebrow: "PROJECT 05",
    title: "Smart Attendance System using Face Recognition",
    shortDescription: "Real-time facial vector matching and automated contactless attendance logging.",
    description: "Computer vision pipeline utilizing OpenCV and deep facial landmark embeddings to identify individuals in multi-subject video streams, instantly recording authenticated timestamps into the database.",
    technicalCallout: "Deep Facial Feature Extraction",
    calloutDetail: "Built with OpenCV and Python facial vector recognition, delivering 95%+ real-time identification accuracy across variable lighting conditions.",
    category: "AI & ML",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1600&auto=format&fit=crop",
    zoomImage: "https://images.unsplash.com/photo-1507146426996-ef05306b995a?q=80&w=1600&auto=format&fit=crop",
    githubUrl: "https://github.com/SURIYAKUMARE",
    liveUrl: "https://github.com/SURIYAKUMARE",
    featured: true,
    order_index: 5,
    year: "2026",
    client: "Autonomous Systems R&D",
    role: "Computer Vision & AI Engineer",
    technologies: ["Python", "OpenCV", "Facial Embeddings", "CNN", "SQL Database"],
    metrics: [
      { label: "Recognition Acc.", value: "95.4%" },
      { label: "Inference Time", value: "< 45ms" },
    ],
    awards: ["Best AI/CV Prototype"],
  },
];
